---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "large"
  labels:
    use: "prometheus"
  name: "prometheus"
  namespace: "prometheus"
spec:
  storageClassName: "large"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "large"
  labels:
    use: "alertmanager"
  name: "alertmanager"
  namespace: "prometheus"
spec:
  storageClassName: "large"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
