---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
data:
  postfix-accounts.cf: |
{{- range .Values.accounts }}
    {{ .account }}|{{ .password }}
{{- end }}
  postfix-virtual.cf: |
{{- range .Values.aliases }}
    {{ .from }} {{ .to }}
{{- end }}
  postfix-main.cf: |
    smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, reject_unauth_pipelining, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname, reject_unknown_recipient_domain, reject_rbl_client zen.spamhaus.org, reject_rbl_client bl.spamcop.net
    recipient_delimiter = -
    {{- if .Values.proxyProtocol.enabled }}
    smtpd_upstream_proxy_protocol = haproxy
    {{- end }}
  dovecot.cf: |
    recipient_delimiter = -
    {{- if .Values.proxyProtocol.enabled }}
    haproxy_trusted_networks = {{ .Values.proxyProtocol.trustedProxyNetwork }}
    service imap-login {
      inet_listener imaps {
        haproxy = yes
      }
    }
    {{- end }}
  spamassassin-rules.cf: |
    score BAYES_99 8.0
    score BAYES_95 5.0
    score BAYES_90 4.0
    score BAYES_80 3.0
    score BAYES_60 2.0
    score BAYES_50 1.0
    score BAYES_40 0.5
    score BAYES_20 -0.5
    score BAYES_05 -2.0
    score BAYES_00 -5.0
    required_score 5.0
  SigningTable: |
    {{- range .Values.opendkim }}
    *@{{ .domain }} {{ .domainkeyHost }}
    {{- end }}
  KeyTable: |
    {{- range .Values.opendkim }}
    {{ .domainkeyHost }} {{ .domain }}:mail:/etc/opendkim/keys/{{ .domain }}.key
    {{- end }}
  TrustedHosts: |
    127.0.0.1
    localhost
---
kind: Secret
apiVersion: v1
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-opendkim
type: Opaque
data:
  {{- range .Values.opendkim }}
  {{ .domain }}.key: '{{ .key | b64enc }}'
  {{- end }}
