{{- if .Values.letsEncrypt.enabled -}}
apiVersion: apps/v1
kind: Ingress
metadata:
{{- if .Values.letsEncrypt.ingress.annotations }}
  annotations:
{{ toYaml .Values.letsEncrypt.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
spec:
  rules:
    - host: "{{ .Values.hostname }}"
      http:
        paths:
          - backend:
            {{- if .Values.letsEncrypt.ingress.backend.serviceName }}
              serviceName: {{ .Values.letsEncrypt.ingress.backend.serviceName }}
              servicePort: {{ .Values.letsEncrypt.ingress.backend.servicePort }}
            {{- else }}
              serviceName: {{ template "defaultBackend.fullname" . }}
              servicePort: {{ .Values.defaultBackend.service.servicePort }}
            {{- end }}
  tls:
    - secretName: {{ template "fullname" . }}-tls
      hosts:
        - "{{ .Values.hostname }}"
{{- end -}}
