apiVersion: v1
kind: Service
metadata:
  name: {{template "fullname" .}}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
  ports:
  - name: smtp
    port: {{ .Values.service.smtpPort }}
    targetPort: smtp
    protocol: TCP
  - name: smtp-auth
    port: {{ .Values.service.smtpAuthPort }}
    targetPort: smtp-auth
    protocol: TCP
  - name: imap-secure
    port: {{ .Values.service.imapSecurePort }}
    targetPort: imap-secure
    protocol: TCP
