apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{template "fullname" .}}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        component: {{template "fullname" .}}
    spec:
      containers:
      - name: kibana
        securityContext:
          privileged: false
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- range $key, $value :=  .Values.env }}
        - name: {{ $key | upper | replace "-" "_" }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
