---
image:
  tag: 1.0.1-ce-alpine
extraVars:
  - name: HMD_DOMAIN
    value: {{ hackmd.domain }}
  - name: HMD_PROTOCOL_USESSL
    value: "true"
  - name: HMD_URL_ADDPORT
    value: "false"
  - name: HMD_ALLOW_FREEURL
    value: "true"
  - name: HMD_ALLOW_ANONYMOUS
    value: "true"
  - name: HMD_GITHUB_CLIENTID
    value: "{{ hackmd.github.client_id }}"
  - name: HMD_GITHUB_CLIENTSECRET
    value: "{{ hackmd.github.secret }}"
  - name: HMD_EMAIL
    value: "false"
  - name: HMD_ALLOW_EMAIL_REGISTER
    value: "false"
  - name: HMD_IMAGE_UPLOAD_TYPE
    value: "filesystem"

ingress:
  enabled: true
  hosts:
    - {{ hackmd.domain }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  tls:
    - secretName: hackmd-tls
      hosts:
        - {{ hackmd.domain }}

postgresql:
  persistence:
    existingClaim: "hackmd-postgres"

persistence:
  existingClaim: "hackmd"
