configInline:
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - {{ metallb.address }}

# controller contains configuration specific to the MetalLB cluster
# controller.
controller:
  image:
    repository: metallb/controller
    tag: v0.6.2
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 100Mi

# speaker contains configuration specific to the MetalLB speaker
# daemonset.
speaker:
  image:
    repository: metallb/speaker
    tag: v0.6.2
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 100Mi