---
controller:
  kind: Deployment
  service:
    type: LoadBalancer
    loadBalancerIP: "{{ ingress.loadBalancerIP }}"
  stats:
    enabled: true
  # config:
  #   proxy-real-ip-cidr: "{{ ingress.proxy_real_ip_cidr }}"
  image:
    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: "0.14.0"

  livenessProbe:
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 5
    port: 10254
  readinessProbe:
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 5
    port: 10254


rbac:
  create: true
{% if ingress.tcp %}
tcp:
  {%- for port, service in ingress.tcp.items() %}
  {{ port }}: "{{ service }}"
  {%- endfor %}
{%- endif %}
