---
apiVersion: v1
kind: Service
metadata:
  name: chrome-headless
  labels:
    app: chrome
spec:
  type: ClusterIP
  selector:
    app: chrome
  ports:
  - port: 4444
    targetPort: 4444
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chrome-headless
  labels:
    app: chrome
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: chrome-headless
      labels:
        app: chrome
    spec:
      serviceAccountName: default
      containers:
      - image: "yukinying/chrome-headless-browser-selenium:latest"
        imagePullPolicy: Always
        name: chrome-headless
        securityContext:
          privileged: false
          capabilities:
            add: ["SYS_ADMIN"]
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 512Mi
        ports:
        - containerPort: 4444
          name: webdriver
          protocol: TCP