---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: gluster.org/glusterfs-simple
parameters:
  brickrootPaths: {{ gluster.storageclass.slow.brickrootPaths }}
  volumeType: "replica 3"
  forceCreate: "true"
  namespace: "storage"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: large
provisioner: gluster.org/glusterfs-simple
parameters:
  brickrootPaths: {{ gluster.storageclass.slow.brickrootPaths }}
  volumeType: ""
  forceCreate: "true"
  namespace: "storage"
