---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
apiVersion: v1
kind: Service
metadata:
  name: core-dns
  namespace: kube-system
  labels:
    k8s-app: core-dns
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: core-dns
  clusterIP: 10.254.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-dns
  namespace: kube-system
data:
  Corefile: |-
    .:53 {
        kubernetes cluster.local {
          upstream 8.8.8.8 8.8.4.4
        }
        file /etc/coredns/records.db vanilla.life
        proxy . /etc/resolv.conf
        health
    }
  records.db: |-
    @       IN      SOA     ns.vanilla.life. root.vanilla.life. (
            2008082901
            28800
            14400
            3600000
            86400 )

                    IN      NS              ns.vanilla.life.
                    IN      A               192.168.1.101
    *               IN      A               192.168.1.101
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: core-dns
  namespace: kube-system
  labels:
    k8s-app: core-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: core-dns
  template:
    metadata:
      labels:
        k8s-app: core-dns
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      hostNetwork: true
      dnsPolicy: Default
      containers:
      - name: "coredns"
        image: "coredns/coredns:006"
        imagePullPolicy: IfNotPresent
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      volumes:
        - name: config-volume
          configMap:
            name: core-dns
            items:
            - key: Corefile
              path: Corefile
            - key: records.db
              path: records.db
