apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{template "fullname" .}}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        component: {{template "fullname" .}}
    spec:
      containers:
      - name: cerebro
        securityContext:
          privileged: false
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          timeoutSeconds: 1
          successThreshold: 1
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- range $key, $value :=  .Values.env }}
        - name: {{ $key | upper | replace "-" "_" }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /cerebro/conf
      volumes:
      - name: config-volume
        configMap:
          name: {{template "fullname" .}}
