---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
  labels:
    use: "gitlab"
  name: gitlab-redis
  namespace: gitlab
spec:
  storageClassName: "slow"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
  labels:
    use: "gitlab"
  name: gitlab-postgres
  namespace: gitlab
spec:
  storageClassName: "slow"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
  labels:
    use: "gitlab"
  name: gitlab
  namespace: gitlab
spec:
  storageClassName: "slow"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
