config:
  LEGO_EMAIL: yuan-lego@fraction.jp
  # LEGO_URL: https://acme-v01.api.letsencrypt.org/directory

rbac:
  create: true

resources:
  limits:
    cpu: 20m
    memory: 48Mi
  requests:
    cpu: 20m
    memory: 48Mi
